AllCops:
  Excludes:
    - db/schema.rb
    - config/initializers/devise.rb
    - bin/bundle
    - vendor/**/*.rb
    - gemfiles/vendor/bundle/**/*.rb

# https://github.com/rubocop/rubocop/issues/9832
inherit_mode:
  merge:
    - Exclude
