AllCops:
  Excludes:
    - db/schema.rb
    - db/migrate/*.rb
    - config/initializers/devise.rb
    - bin/bundle
    - vendor/**/*.rb
    - gemfiles/vendor/bundle/**/*.rb
  
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/GlobalVars:
  Enabled: false

# https://github.com/rubocop/rubocop/issues/9832
inherit_mode:
  merge:
    - Exclude
