version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: myapp_development
    ports:
      - "5432:5432"
  
  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    command: sh -c "bin/dev"
    tty: true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://user:password@db/myapp_development
      REDIS_URL: redis://redis:6379/1

volumes:
  postgres_data:
